---
title: "Comparitive Analysis"
author: "Craig Orman, Naga Vempati, Dr. Heike Hofmann"
date: "2022-12-09"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require(fastDummies)) install.packages('fastDummies')
if (!require(tidyverse)) install.packages('tidyverse')
if (!require(ggplot2)) install.packages('ggplot2')
if (!require(ggpubr)) install.packages('ggpubr')
library(fastDummies)
library(tidyverse)
library(ggplot2)
library(ggpubr)

```

Staging
```{r}
full_data = read.csv(file = "../data/std_and_cropped_data_12_20_2022.csv", header=TRUE)
```

```{r}

full_data = full_data %>% mutate(
  Quality = factor(Quality, levels=c("Good", "Tiny Problems", "Problematic", "Bad", "Yikes")),
  Problem = factor(Problem)
)

```


## Functions
```{r}
comparison <- function(df, feature) {

  upper = max(max(df[,1]), max(df[,2]))
  upper = upper * 1.1
  scatty = ggplot(df, aes(x=df[,1], y=df[,2])) +
    geom_point(data = select(df,-3), col="grey") +
    geom_point(size=2, pch=21, aes(fill=factor(df[,3]))) +
    scale_fill_manual(values=c("blue","green","yellow", "orange", "red")) + 
    xlim(0,upper) +
    ylim(0,upper) +
    xlab("Standard") +
    ylab("Cropped") +
    ggtitle(feature) +
    #geom_smooth(method=lm, se = FALSE, aes(group = 1)) +
    #stat_regline_equation(label.y = upper, aes(label = ..eq.label..)) +
    #stat_regline_equation(label.y = upper*0.9, aes(label = ..rr.label..)) +
    facet_grid(~df[,3])
  
  boxy = boxplot(df[,1], df[,2],
          horizontal = TRUE,
          main = feature,
          names = c("Standard", "Cropped"),
          col = c("red", "blue"))
          
  print(scatty)
  boxy
  summ = data.frame(min = numeric(),
                  firstQ = numeric(),
                  med = numeric(),
                  mean = numeric(),
                  thirdQ = numeric(),
                  max = numeric())
  
  print(paste("Summary Info of", feature))
  summ[1,] = summary(df[,1])
  summ[2,] = summary(df[,2])
  rownames(summ) = c("Standard", "Cropped")
  print(summ)
}
```

```{r}
comparison(data.frame(full_data$extract_na, full_data$extract_na_cropped, full_data$Quality), feature = "Extract NA")
#comparison(full_data$assess_percentile_na_proportion, full_data$assess_percentile_na_proportion_cropped, feature = "Assess percentile NA proportion")
#comparison(full_data$assess_col_na, full_data$assess_col_na_cropped, feature = "assess col NA")
#comparison(full_data$assess_bottomempty, full_data$assess_bottomempty_cropped, feature = "Bottom Empty")
#comparison(full_data$assess_median_na_proportion, full_data$assess_median_na_proportion_cropped, feature = "Assess median NA proportion")
```

```{r}
df = data.frame(full_data$extract_na, full_data$extract_na_cropped, full_data$Quality)
feature = "Extract NA"
upper = max(max(df[,1]), max(df[,2]))
upper = upper * 1.1
ggplot(df, aes(x=df[,1], y=df[,2])) +
    geom_point(data = df[,-3], col="grey", size = 1, aes(group=1)) +
    geom_point(size=2, pch=21, aes(fill=factor(df[,3]), group=2)) +
    scale_fill_manual(values=c("blue","green","yellow", "orange", "red")) + 
    xlim(0,upper) +
    ylim(0,upper) +
    xlab("Standard") +
    ylab("Cropped") +
    ggtitle(feature) +
    geom_smooth(formula = y ~ x, method=lm, se = FALSE) +
    stat_regline_equation(label.y = upper, aes(label = ..eq.label..)) +
    stat_regline_equation(label.y = upper*0.9, aes(label = ..rr.label..)) +
    facet_grid(~df[,3])
```

